import { activityLevel, buildTokenActivity } from './activity.js'
import { formatMoney, formatTokens } from './format.js'
import { localeTag, t, translateText } from './i18n.js'

const COLORS = {
  background: '#1b1a17',
  surface: '#292823',
  line: '#3a3832',
  text: '#eeeae1',
  muted: '#858077',
  accent: '#e26a4e',
  heatmap: ['#292823', '#4b2c24', '#75402f', '#ad513b', '#e26a4e'],
}
const SANS = 'ui-sans-serif, -apple-system, BlinkMacSystemFont, sans-serif'
const MONO = 'ui-monospace, SFMono-Regular, Menlo, monospace'

function roundedRect(ctx, x, y, width, height, radius) {
  ctx.beginPath()
  ctx.roundRect(x, y, width, height, radius)
  ctx.fill()
}

function drawHeader(ctx, title, label) {
  ctx.fillStyle = COLORS.text
  ctx.font = `600 34px ${SANS}`
  ctx.fillText(title, 88, 96)
  ctx.textAlign = 'right'
  ctx.fillStyle = COLORS.muted
  ctx.font = `600 18px ${MONO}`
  ctx.fillText(label.toUpperCase(), 1512, 92)
  ctx.textAlign = 'left'
}

function drawFooter(ctx, participantLabel, locale) {
  ctx.fillStyle = COLORS.line
  ctx.fillRect(88, 797, 1424, 1)
  ctx.fillStyle = COLORS.muted
  ctx.font = `500 17px ${SANS}`
  ctx.fillText(t(locale, '由 Token Killer 生成', 'Generated by Token Killer'), 88, 846)
  ctx.textAlign = 'right'
  ctx.fillStyle = COLORS.text
  ctx.font = `600 18px ${MONO}`
  ctx.fillText(translateText(locale, participantLabel), 1512, 837)
  ctx.fillStyle = COLORS.muted
  ctx.font = `500 16px ${MONO}`
  ctx.fillText(new Date().toLocaleDateString(localeTag(locale)), 1512, 865)
  ctx.textAlign = 'left'
}

function drawHeatmap(ctx, activity) {
  const heatmapX = 88
  const heatmapY = 146
  const gap = 6
  const cellSize = 20
  activity.weeks.forEach((week, weekIndex) => {
    week.days.forEach((day, dayIndex) => {
      const level = day.isFuture ? 0 : activityLevel(day.tokens, activity.dailyPeak)
      ctx.fillStyle = COLORS.heatmap[level]
      roundedRect(
        ctx,
        heatmapX + weekIndex * (cellSize + gap),
        heatmapY + dayIndex * (cellSize + gap),
        cellSize,
        cellSize,
        5,
      )
    })
  })
  ctx.fillStyle = COLORS.muted
  ctx.font = `500 19px ${SANS}`
  activity.monthLabels.forEach((month) => {
    ctx.fillText(month.label, heatmapX + month.index * (cellSize + gap), 355)
  })
}

function drawMetric(ctx, label, value, x, y, width = 340) {
  ctx.fillStyle = COLORS.surface
  roundedRect(ctx, x, y, width, 126, 18)
  ctx.fillStyle = COLORS.muted
  ctx.font = `500 19px ${SANS}`
  ctx.fillText(label, x + 25, y + 40)
  ctx.fillStyle = COLORS.text
  ctx.font = `650 43px ${MONO}`
  ctx.fillText(value, x + 25, y + 96)
}

function drawActivityStory(ctx, data) {
  const { activity, todayTokens, totalTokens, totalCost, globalRank, tier, locale } = data
  drawHeader(ctx, t(locale, 'Token 活动', 'Token activity'), t(locale, '年度轨迹', 'Year in tokens'))
  drawHeatmap(ctx, activity)
  ctx.fillStyle = COLORS.line
  ctx.fillRect(88, 405, 1424, 1)
  drawMetric(ctx, t(locale, '今日消耗', 'Burned today'), formatTokens(todayTokens), 88, 454)
  drawMetric(ctx, t(locale, '累计消耗', 'Lifetime burn'), formatTokens(totalTokens), 450, 454)
  drawMetric(ctx, t(locale, '估算成本', 'Estimated cost'), formatMoney(totalCost), 812, 454)
  ctx.fillStyle = COLORS.accent
  roundedRect(ctx, 1174, 454, 338, 126, 18)
  ctx.fillStyle = COLORS.background
  ctx.font = `700 18px ${SANS}`
  ctx.fillText(t(locale, '当前排位', 'Current rank'), 1199, 494)
  ctx.font = `700 28px ${MONO}`
  ctx.fillText(globalRank ? `#${globalRank}` : t(locale, '冲击中', 'Climbing'), 1199, 535)
  ctx.font = `600 17px ${SANS}`
  ctx.fillText(translateText(locale, tier?.fullName || '火种 III'), 1199, 561)
  ctx.fillStyle = COLORS.surface
  roundedRect(ctx, 88, 632, 1424, 116, 18)
  ctx.fillStyle = COLORS.text
  ctx.font = `700 25px ${MONO}`
  ctx.fillText('TOKEN KILLER', 118, 679)
  ctx.fillStyle = COLORS.muted
  ctx.font = `500 18px ${SANS}`
  ctx.fillText(t(locale, '每一格都来自 usage 运行记录', 'Every cell comes from recorded usage'), 118, 716)
}

function drawRankStory(ctx, data) {
  const { totalTokens, totalCost, globalRank, tier, locale } = data
  drawHeader(ctx, t(locale, '段位战报', 'Rank report'), t(locale, '燃烧排位', 'Burn rank'))
  ctx.fillStyle = COLORS.accent
  roundedRect(ctx, 88, 154, 188, 188, 28)
  ctx.fillStyle = COLORS.background
  ctx.font = `750 28px ${MONO}`
  ctx.textAlign = 'center'
  ctx.fillText('RANK', 182, 260)
  ctx.textAlign = 'left'
  ctx.fillStyle = COLORS.muted
  ctx.font = `600 20px ${SANS}`
  ctx.fillText(t(locale, '当前段位', 'Current rank'), 330, 188)
  ctx.fillStyle = COLORS.text
  ctx.font = `700 82px ${SANS}`
  ctx.fillText(translateText(locale, tier?.fullName || '火种 III'), 330, 285)
  ctx.fillStyle = COLORS.muted
  ctx.font = `500 22px ${SANS}`
  ctx.fillText(
    tier?.nextName
      ? t(locale, `距离 ${tier.nextName} 还差 ${formatTokens(tier.tokensToNext)} Token`, `${formatTokens(tier.tokensToNext)} Token to ${translateText(locale, tier.nextName)}`)
      : t(locale, '已经抵达最高段位', 'Highest rank reached'),
    333,
    332,
  )
  ctx.fillStyle = COLORS.line
  ctx.fillRect(88, 397, 1424, 1)
  drawMetric(ctx, t(locale, '全球排名', 'Global rank'), globalRank ? `#${globalRank}` : t(locale, '未上榜', 'Unranked'), 88, 452, 430)
  drawMetric(ctx, t(locale, '累计消耗', 'Lifetime burn'), formatTokens(totalTokens), 540, 452, 430)
  drawMetric(ctx, t(locale, '估算成本', 'Estimated cost'), formatMoney(totalCost), 992, 452, 520)
  ctx.fillStyle = COLORS.text
  ctx.font = `650 32px ${SANS}`
  ctx.fillText(t(locale, '下一把火，会把你推向哪里？', 'Where will the next burn take you?'), 88, 681)
  ctx.fillStyle = COLORS.muted
  ctx.font = `500 19px ${SANS}`
  ctx.fillText(t(locale, '永久段位不会因赛季或排行榜变化而重置。', 'Lifetime rank does not reset with seasons or leaderboards.'), 88, 721)
}

function wrapText(ctx, text, x, y, maxWidth, lineHeight, maxLines = 3) {
  const words = String(text || '').split(/\s+/)
  const lines = []
  let current = ''
  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word
    if (ctx.measureText(candidate).width <= maxWidth || !current) {
      current = candidate
    } else {
      lines.push(current)
      current = word
    }
  }
  if (current) lines.push(current)
  lines.slice(0, maxLines).forEach((line, index) => ctx.fillText(line, x, y + index * lineHeight))
}

function drawAchievementStory(ctx, data) {
  const { achievement, achievements, totalTokens, locale } = data
  drawHeader(ctx, t(locale, '成就战报', 'Achievement report'), t(locale, '燃烧成就', 'Burn achievement'))
  ctx.fillStyle = COLORS.accent
  roundedRect(ctx, 88, 154, 238, 238, 34)
  ctx.fillStyle = COLORS.background
  ctx.font = `750 24px ${MONO}`
  ctx.textAlign = 'center'
  ctx.fillText('UNLOCKED', 207, 281)
  ctx.textAlign = 'left'
  ctx.fillStyle = COLORS.muted
  ctx.font = `600 20px ${SANS}`
  ctx.fillText(t(locale, '新成就已解锁', 'Achievement unlocked'), 382, 188)
  ctx.fillStyle = COLORS.text
  ctx.font = `700 72px ${SANS}`
  const title = locale === 'en' ? achievement?.titleEn : achievement?.title
  ctx.fillText(title || t(locale, '第一把火', 'First spark'), 382, 278)
  ctx.fillStyle = COLORS.muted
  ctx.font = `500 23px ${SANS}`
  wrapText(
    ctx,
    locale === 'en' ? achievement?.descriptionEn : achievement?.description,
    385,
    330,
    1080,
    34,
    2,
  )
  ctx.fillStyle = COLORS.line
  ctx.fillRect(88, 449, 1424, 1)
  drawMetric(ctx, t(locale, '已解锁', 'Unlocked'), `${achievements?.unlockedCount || 0} / ${achievements?.totalCount || 0}`, 88, 505, 430)
  drawMetric(ctx, t(locale, '累计消耗', 'Lifetime burn'), `${formatTokens(totalTokens)} Token`, 540, 505, 972)
  ctx.fillStyle = COLORS.text
  ctx.font = `650 30px ${SANS}`
  ctx.fillText(t(locale, '下一枚成就，正在等待你的 Token。', 'Your next achievement is waiting for more tokens.'), 88, 711)
}

export function exportShareCard({
  story = 'activity',
  todayTokens = 0,
  totalTokens = 0,
  totalCost = 0,
  participantLabel = '燃烧者',
  globalRank = null,
  tier = null,
  locale = 'zh-CN',
  activity: suppliedActivity,
  achievement = null,
  achievements = null,
}) {
  const activity = suppliedActivity || buildTokenActivity([], { locale: localeTag(locale) })
  const canvas = document.createElement('canvas')
  canvas.width = 1600
  canvas.height = 900
  const ctx = canvas.getContext('2d')
  ctx.fillStyle = COLORS.background
  ctx.fillRect(0, 0, canvas.width, canvas.height)
  const data = {
    activity,
    todayTokens,
    totalTokens,
    totalCost,
    participantLabel,
    globalRank,
    tier,
    locale,
    achievement,
    achievements,
  }
  if (story === 'rank') drawRankStory(ctx, data)
  else if (story === 'achievement' && achievement) drawAchievementStory(ctx, data)
  else drawActivityStory(ctx, data)
  drawFooter(ctx, participantLabel, locale)

  const link = document.createElement('a')
  link.href = canvas.toDataURL('image/png')
  link.download = `token-killer-${story}-${new Date().toISOString().slice(0, 10)}.png`
  link.click()
}
